branch-defaults:
  default:
    environment: finalelbdevsecops-env
    group_suffix: null
  master:
    environment: try2devdinal-env
    group_suffix: null
global:
  application_name: finalelbdevsecopstry1
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.7
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
